DROP TABLE IF EXISTS data;
CREATE TABLE data
(
	data_id INTEGER PRIMARY KEY AUTOINCREMENT,   
	x1 INTEGER,
    x2 INTEGER,
    x3 INTEGER,
    x4 INTEGER,
    x5 INTEGER,
    x6 INTEGER,
    x7 INTEGER,
    x8 INTEGER,
    x9 INTEGER,
    x10 INTEGER,
    y TEXT
);

DELETE FROM data WHERE data_id > 1;